### ISSUE TITLE
Les examples ne sont pas complets.

### ISSUE THREAD

**Issue by YPatois** [cpierquet/WriteOngrid#1]
Bonjour,

- 3.6 example "détaillé" n'inclut rien: il ne peut donc pas compiler.
- 3.7 example "détaillé" ne compile pas sans ajouter \usepackage{xfp} qui fourni \fpeval utilisé par WriteOnGrid.sty

(Ubuntu 22.04 LTS avec liveTeX fourni (2021)).

Merci.

**Comment by cpierquet** [comment]
Bonjour, merci pour les remontées. Votre version de TeXlive est un peu ancienne, il est recommandé d'utiliser la dernière version, avec les packages à jour.

1/ concernant xfp, les récentes versions du noyau incluent les commandes de xfp par défaut, il n'est donc (plus) utile de le charger :
![image](https://github.com/cpierquet/WriteOngrid/assets/45103962/45e84c05-8e6b-41e8-ae9b-af2d4e21cb8f)

2/ pour l'exemple 3.6, je n'ai pas remis le préambule avec les packages nécessaires, mais cela compile :
![image](https://github.com/cpierquet/WriteOngrid/assets/45103962/c9fe57b6-a581-40ea-a1a7-2d6f13217a14)
