### ISSUE TITLE
Options de marge pour `PleinePageCinqCinq`

### ISSUE THREAD

**Issue by Nora-n** [cpierquet/WriteOngrid#2]
Bonjour,

Tout d'abord, merci pour ce paquet, et bravo pour sa réalisation !

J'aimerais beaucoup avoir la possibilité de changer la position de la marge dans l'environnement `PleinePageCinqCinq`. L'option `CouleurMarge=red!75` fonctionne bien, mais pas `Marge=2.7` par exemple, et si je la redéfinis moi-même dans le document `.tex` avec `\xdef\CCFullMargeG{2.7}`, la première marge reste affichée et la largeur de la ligne avec le mode `auto` ne marche plus, il faudrait la redéfinir à chaque commande `LignePapierCinqCinq`.

Il suffirait pour cela d'ajouter par exemple un paramètre optionnel `o` ligne 579 du code, puis d'imbriquer par exemple les `\IfEq` (qui pourraient d'ailleurs être regroupés en un seul `\IfEqCase` il me semble) en utilisant ce paramètre `#2`. Il serait intéressant d'avoir la même option pour la marge haute par ailleurs.

Merci pour votre attention !

**Comment by cpierquet** [comment]
Merci pour le retour, je vais regarder cela :-)

**Comment by Nora-n** [comment]
Fantastique, merci pour la rapidité d'exécution !

Malheureusement je vais devoir attendre de mettre à jour ma distribution TeXlive pour en profiter… ce qui risque de prendre un certain temps.

Le problème peut être clos je pense.

**Comment by cpierquet** [comment]
J'ai envoyé la mise à jour, elle devrait être disponible demain ou après-demain sans doute.
Sinon je vais mettre à jour le dépôt github, donc le fichier sty pourra dépanner temporairement.
